### ISSUE TITLE
Create logging control.

### ISSUE THREAD

**Issue by sharov-am** [lacmus-foundation/lacmus-app#34]
We need to create control where it is possilbe to see current events -- warn messages, error, info . Just some TextBox or similar control where logs are collected for current user session. It doesn't exclude file logs which are persisted among all user sessions and probably should be more verbose -- contain debug messages.

**Comment by gosha20777** [comment]
https://github.com/AvaloniaUI/Avalonia/wiki/3rd-Party-Control-Gallery - look at here.
we can use this control to output logs - https://github.com/VitalElement/AvalonStudio.TerminalEmulator

We can also rewrite our interface using the dock control, so that we can move panels in the same way as in Visual Studio.
- On the right side is a tab with a list of photos.
- In the center is viewport
- Bottom is event log in terminal emulator

**Comment by gosha20777** [comment]
this links might be useful
- https://github.com/wieslawsoltes/Core2D
- https://github.com/zkSNACKs/WalletWasabi
- https://github.com/VitalElement/AvalonStudio

**Comment by gosha20777** [comment]
look at issue #35 and `dev_doc_ui_#35` branch

**Comment by gosha20777** [comment]
![Screenshot from 2022-08-11 11-54-35](https://user-images.githubusercontent.com/25365364/184099661-8d8eb860-1aa4-458b-9071-07f0e0635c59.png)
