### ISSUE TITLE
Incorret number in left poginator

### ISSUE THREAD

**Issue by gserrg** [lacmus-foundation/lacmus-app#67]
Show `0 of 2` and `1 of 2`.  Require increment number

**Comment by gosha20777** [comment]
- fix at 7ddc6e2
- Also fix bug: if you switch the page and select a non-zero element, then on the next page the zero element of the previous page will be displayed. 
- added a good buttons instead of `>` arrows.

![Снимок экрана от 2020-04-01 22-40-49](https://user-images.githubusercontent.com/25365364/78179448-e45e6100-7469-11ea-8a8a-40db64fe088e.png)
